name: project_camera
description: A new Flutter project.


environment:
  sdk: "^3.5.0"


version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+2
  permission_handler: ^11.3.1
  path_provider: ^2.1.5
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
